import type {
  AchievementDef,
  AreaDef,
  BagDef,
  FishDef,
  HookDef,
  LineDef,
  MissionDef,
  Rarity,
  RodDef,
} from "./types";

export const RARITY_ORDER: Rarity[] = [
  "common",
  "uncommon",
  "rare",
  "epic",
  "legendary",
  "mythic",
];

export const RARITY_COLOR: Record<Rarity, string> = {
  common: "#c9d7de",
  uncommon: "#4ade80",
  rare: "#38bdf8",
  epic: "#c084fc",
  legendary: "#fb923c",
  mythic: "#fb7185",
};

export const AREAS: AreaDef[] = [
  {
    id: "beach",
    name: "Praia Inicial",
    blurb: "Águas mornas e claras. Peixes pequenos, mas o mar já chama.",
    maxDepth: 25,
    price: 0,
    level: 1,
    skyTop: "#9bd6f0",
    skyBot: "#e7f6ff",
    waterTop: "#4ad4dc",
    waterBot: "#0f6f86",
  },
  {
    id: "open",
    name: "Mar Aberto",
    blurb: "Horizonte sem fim. Cardumes, atuns e o primeiro ouro de verdade.",
    maxDepth: 60,
    price: 2000,
    level: 4,
    skyTop: "#6eb8e0",
    skyBot: "#d4eefc",
    waterTop: "#2bb8c9",
    waterBot: "#0a4d68",
  },
  {
    id: "reef",
    name: "Recife de Coral",
    blurb: "Um jardim submarino. Cores, perigo e tesouros entre os corais.",
    maxDepth: 100,
    price: 12000,
    level: 9,
    skyTop: "#5ec4e0",
    skyBot: "#ffe8d2",
    waterTop: "#21c4b0",
    waterBot: "#0a5a72",
  },
  {
    id: "deep",
    name: "Mar Profundo",
    blurb: "A luz rareia. Predadores grandes caçam no azul-escuro.",
    maxDepth: 180,
    price: 50000,
    level: 16,
    skyTop: "#4a90b8",
    skyBot: "#b8d4e8",
    waterTop: "#1a7a9a",
    waterBot: "#06324a",
  },
  {
    id: "abyss",
    name: "Abismo",
    blurb: "Noite eterna. Só os lanternas e os dentes sobrevivem aqui.",
    maxDepth: 300,
    price: 180000,
    level: 24,
    skyTop: "#2a4a68",
    skyBot: "#7a9bb0",
    waterTop: "#0d4a62",
    waterBot: "#031820",
  },
  {
    id: "trench",
    name: "Fossa Oceânica",
    blurb: "Pressão que esmaga aço. Criaturas que a ciência nega.",
    maxDepth: 500,
    price: 600000,
    level: 35,
    skyTop: "#1a3048",
    skyBot: "#4a6880",
    waterTop: "#0a3048",
    waterBot: "#01080e",
  },
  {
    id: "mystery",
    name: "Zona Misteriosa",
    blurb: "Além do mapa. O mar aqui não é mais água — é um reino.",
    maxDepth: 800,
    price: 2000000,
    level: 48,
    skyTop: "#14182a",
    skyBot: "#3a2a58",
    waterTop: "#1a2458",
    waterBot: "#05010c",
  },
];

export const RODS: RodDef[] = [
  {
    id: "wood",
    name: "Vara de Madeira",
    depth: 20,
    force: 10,
    price: 0,
    color: "#b07a3a",
    accent: "#e8c48a",
    blurb: "Simples e honesta. Serve para a beira.",
  },
  {
    id: "bamboo",
    name: "Vara de Bambu",
    depth: 35,
    force: 16,
    price: 180,
    color: "#c4d36a",
    accent: "#6a8a32",
    blurb: "Leve, flexível, alcança o fundo da praia.",
  },
  {
    id: "fiber",
    name: "Vara de Fibra",
    depth: 50,
    force: 25,
    price: 500,
    color: "#4aa3c8",
    accent: "#e8f4fa",
    blurb: "O primeiro equipamento de verdade.",
  },
  {
    id: "carbon",
    name: "Vara de Carbono",
    depth: 75,
    force: 40,
    price: 1800,
    color: "#2a2e36",
    accent: "#7ad4e8",
    blurb: "Rígida e precisa. Mar aberto sem medo.",
  },
  {
    id: "pro",
    name: "Vara Profissional",
    depth: 100,
    force: 55,
    price: 5000,
    color: "#1e5a8a",
    accent: "#f0c14b",
    blurb: "Usada por campeões de torneio.",
  },
  {
    id: "titanium",
    name: "Vara de Titânio",
    depth: 150,
    force: 80,
    price: 15000,
    color: "#8aa0b4",
    accent: "#e8eef4",
    blurb: "Leve como pena, forte como âncora.",
  },
  {
    id: "abyss",
    name: "Vara Abissal",
    depth: 250,
    force: 110,
    price: 50000,
    color: "#123848",
    accent: "#3ee0c0",
    blurb: "Forjada para a noite do oceano.",
  },
  {
    id: "trench",
    name: "Vara da Fossa",
    depth: 350,
    force: 150,
    price: 150000,
    color: "#0a1c28",
    accent: "#7a5cff",
    blurb: "Resiste à pressão que quebra ossos.",
  },
  {
    id: "legend",
    name: "Vara Lendária",
    depth: 500,
    force: 200,
    price: 500000,
    color: "#8a4a12",
    accent: "#ffd078",
    blurb: "Dizem que fisgou o primeiro leviatã.",
  },
  {
    id: "mythic",
    name: "Vara Mítica",
    depth: 800,
    force: 280,
    price: 2000000,
    color: "#4a1030",
    accent: "#ff6b9a",
    blurb: "Não foi feita por mãos humanas.",
  },
];

export const HOOKS: HookDef[] = [
  {
    id: "basic",
    name: "Anzol Comum",
    price: 0,
    hook: 0,
    rare: 0,
    size: 0,
    blurb: "Faz o serviço. Sem milagre.",
  },
  {
    id: "sharp",
    name: "Anzol Afiado",
    price: 220,
    hook: 0.08,
    rare: 0.02,
    size: 0.04,
    blurb: "Morde mais fundo. Menos peixe escapa.",
  },
  {
    id: "double",
    name: "Anzol Duplo",
    price: 900,
    hook: 0.15,
    rare: 0.04,
    size: 0.1,
    blurb: "Dois ganchos, peixes maiores.",
  },
  {
    id: "gold",
    name: "Anzol Dourado",
    price: 4200,
    hook: 0.12,
    rare: 0.12,
    size: 0.15,
    blurb: "Atrai o que brilha no fundo.",
  },
  {
    id: "diamond",
    name: "Anzol de Diamante",
    price: 22000,
    hook: 0.25,
    rare: 0.2,
    size: 0.25,
    blurb: "Quase não solta. Raros notam o brilho.",
  },
  {
    id: "abyss",
    name: "Anzol Abissal",
    price: 85000,
    hook: 0.35,
    rare: 0.32,
    size: 0.35,
    blurb: "Temperado em fossas. Nada foge fácil.",
  },
  {
    id: "mythic",
    name: "Anzol Mítico",
    price: 420000,
    hook: 0.5,
    rare: 0.48,
    size: 0.5,
    blurb: "O peixe sente o destino e vem.",
  },
];

export const LINES: LineDef[] = [
  {
    id: "nylon",
    name: "Linha de Nylon",
    price: 0,
    resist: 12,
    depthBonus: 0,
    pull: 0,
    blurb: "Estica, treme, às vezes arrebenta.",
  },
  {
    id: "strong",
    name: "Linha Reforçada",
    price: 260,
    resist: 22,
    depthBonus: 5,
    pull: 0.08,
    blurb: "Um pouco mais de folga na briga.",
  },
  {
    id: "braid",
    name: "Linha de Trança",
    price: 1300,
    resist: 40,
    depthBonus: 10,
    pull: 0.16,
    blurb: "Fina, forte, desce rápido.",
  },
  {
    id: "kevlar",
    name: "Linha de Kevlar",
    price: 6500,
    resist: 70,
    depthBonus: 20,
    pull: 0.24,
    blurb: "Quase não cede. Profundidade extra.",
  },
  {
    id: "abyss",
    name: "Linha Abissal",
    price: 32000,
    resist: 120,
    depthBonus: 40,
    pull: 0.36,
    blurb: "Tecida para a escuridão.",
  },
  {
    id: "legend",
    name: "Linha Lendária",
    price: 160000,
    resist: 200,
    depthBonus: 80,
    pull: 0.5,
    blurb: "Dizem que nunca arrebentou. Quase.",
  },
];

export const BAGS: BagDef[] = [
  {
    id: "sack",
    name: "Saco de Lona",
    price: 0,
    capacity: 10,
    blurb: "Cabe o almoço. Só o almoço.",
  },
  {
    id: "small",
    name: "Mochila Pequena",
    price: 320,
    capacity: 20,
    blurb: "Duas vezes mais peixe por viagem.",
  },
  {
    id: "medium",
    name: "Mochila Média",
    price: 1600,
    capacity: 40,
    blurb: "Para quem já vive no cais.",
  },
  {
    id: "large",
    name: "Mochila Grande",
    price: 8000,
    capacity: 75,
    blurb: "Cardume inteiro, se você aguentar.",
  },
  {
    id: "chest",
    name: "Baú do Pescador",
    price: 26000,
    capacity: 120,
    blurb: "Gelo, divisórias, respeito.",
  },
  {
    id: "hold",
    name: "Porão do Barco",
    price: 85000,
    capacity: 200,
    blurb: "Agora você tem um barco de verdade.",
  },
  {
    id: "warehouse",
    name: "Armazém",
    price: 260000,
    capacity: 350,
    blurb: "O mercado espera. Você entrega.",
  },
];

function F(p: FishDef): FishDef {
  return p;
}

export const FISH: FishDef[] = [
  F({
    id: "sardinha",
    name: "Sardinha",
    rarity: "common",
    minDepth: 0,
    maxDepth: 14,
    minWeight: 0.08,
    maxWeight: 0.28,
    value: 7,
    chance: 110,
    areas: ["beach"],
    strength: 6,
    xp: 8,
    shape: "sardine",
    body: "#8aa8b8",
    belly: "#e8f0f4",
    fin: "#6a8898",
    accent: "#d8e8f0",
    pattern: "stripe",
  }),
  F({
    id: "manjuba",
    name: "Manjuba",
    rarity: "common",
    minDepth: 0,
    maxDepth: 10,
    minWeight: 0.04,
    maxWeight: 0.14,
    value: 5,
    chance: 100,
    areas: ["beach"],
    strength: 4,
    xp: 6,
    shape: "sardine",
    body: "#c8d070",
    belly: "#f4f0c8",
    fin: "#9aa048",
    accent: "#e8e890",
    pattern: "none",
  }),
  F({
    id: "tainha",
    name: "Tainha",
    rarity: "common",
    minDepth: 0,
    maxDepth: 18,
    minWeight: 0.4,
    maxWeight: 1.4,
    value: 11,
    chance: 85,
    areas: ["beach", "open"],
    strength: 10,
    xp: 10,
    shape: "tuna",
    body: "#6a8a9a",
    belly: "#d8e4ea",
    fin: "#4a6a78",
    accent: "#b8ccd4",
    pattern: "scale",
  }),
  F({
    id: "tilapia",
    name: "Tilápia",
    rarity: "common",
    minDepth: 1,
    maxDepth: 16,
    minWeight: 0.5,
    maxWeight: 2.0,
    value: 13,
    chance: 80,
    areas: ["beach"],
    strength: 12,
    xp: 11,
    shape: "round",
    body: "#c4a46a",
    belly: "#f0e0b8",
    fin: "#8a7048",
    accent: "#5a8a4a",
    pattern: "band",
  }),
  F({
    id: "anchova",
    name: "Anchova",
    rarity: "common",
    minDepth: 4,
    maxDepth: 22,
    minWeight: 0.4,
    maxWeight: 1.8,
    value: 15,
    chance: 75,
    areas: ["beach", "open"],
    strength: 14,
    xp: 12,
    shape: "tuna",
    body: "#5a9aaa",
    belly: "#d0e8ee",
    fin: "#3a7080",
    accent: "#8ac4d0",
    pattern: "stripe",
  }),
  F({
    id: "carapau",
    name: "Carapau",
    rarity: "uncommon",
    minDepth: 6,
    maxDepth: 25,
    minWeight: 0.3,
    maxWeight: 1.5,
    value: 24,
    chance: 42,
    areas: ["beach", "open"],
    strength: 16,
    xp: 18,
    shape: "sardine",
    body: "#3a8aaa",
    belly: "#c8e8f0",
    fin: "#e8a030",
    accent: "#f0d060",
    pattern: "stripe",
  }),
  F({
    id: "palhaco",
    name: "Peixe-palhaço",
    rarity: "uncommon",
    minDepth: 2,
    maxDepth: 14,
    minWeight: 0.08,
    maxWeight: 0.28,
    value: 30,
    chance: 34,
    areas: ["beach", "reef"],
    strength: 8,
    xp: 20,
    shape: "clown",
    body: "#e87820",
    belly: "#f8d090",
    fin: "#e8a040",
    accent: "#fff8f0",
    pattern: "band",
  }),
  F({
    id: "robalo",
    name: "Robalo",
    rarity: "uncommon",
    minDepth: 8,
    maxDepth: 28,
    minWeight: 0.9,
    maxWeight: 4.2,
    value: 38,
    chance: 30,
    areas: ["beach", "open"],
    strength: 22,
    xp: 24,
    shape: "tuna",
    body: "#7a9aaa",
    belly: "#e0ecee",
    fin: "#4a6878",
    accent: "#c8dce0",
    pattern: "spot",
  }),
  F({
    id: "cavalo",
    name: "Cavalo-marinho",
    rarity: "rare",
    minDepth: 1,
    maxDepth: 12,
    minWeight: 0.02,
    maxWeight: 0.09,
    value: 70,
    chance: 12,
    areas: ["beach", "reef"],
    strength: 7,
    xp: 42,
    shape: "seahorse",
    body: "#e07090",
    belly: "#f8c0d0",
    fin: "#c05078",
    accent: "#f8e0a0",
    pattern: "none",
  }),
  F({
    id: "borboleta",
    name: "Peixe-borboleta",
    rarity: "rare",
    minDepth: 3,
    maxDepth: 18,
    minWeight: 0.1,
    maxWeight: 0.45,
    value: 78,
    chance: 12,
    areas: ["beach", "reef"],
    strength: 9,
    xp: 46,
    shape: "round",
    body: "#f0d040",
    belly: "#fff4c0",
    fin: "#e8a020",
    accent: "#303030",
    pattern: "band",
  }),
  F({
    id: "pargo-rosa",
    name: "Pargo-rosa",
    rarity: "epic",
    minDepth: 12,
    maxDepth: 28,
    minWeight: 1.4,
    maxWeight: 5.5,
    value: 210,
    chance: 4.2,
    areas: ["beach", "open"],
    strength: 36,
    xp: 110,
    shape: "tuna",
    body: "#e07088",
    belly: "#f8d0d8",
    fin: "#b04058",
    accent: "#f0a0b0",
    pattern: "scale",
  }),
  F({
    id: "peixe-rei",
    name: "Peixe-rei",
    rarity: "legendary",
    minDepth: 16,
    maxDepth: 25,
    minWeight: 2.2,
    maxWeight: 7.0,
    value: 1400,
    chance: 0.7,
    areas: ["beach"],
    strength: 55,
    xp: 380,
    shape: "marlin",
    body: "#f0c850",
    belly: "#fff3c8",
    fin: "#d09020",
    accent: "#fff8e0",
    glow: "#ffe080",
    pattern: "glow",
  }),

  F({
    id: "bagre",
    name: "Bagre",
    rarity: "common",
    minDepth: 6,
    maxDepth: 40,
    minWeight: 0.6,
    maxWeight: 3.5,
    value: 14,
    chance: 90,
    areas: ["open"],
    strength: 18,
    xp: 12,
    shape: "flat",
    body: "#6a5a48",
    belly: "#c8b8a0",
    fin: "#4a3c30",
    accent: "#8a7a64",
    pattern: "none",
  }),
  F({
    id: "cavala",
    name: "Cavala",
    rarity: "common",
    minDepth: 10,
    maxDepth: 48,
    minWeight: 0.5,
    maxWeight: 2.8,
    value: 16,
    chance: 88,
    areas: ["open"],
    strength: 20,
    xp: 13,
    shape: "tuna",
    body: "#3a6a88",
    belly: "#d0e4ec",
    fin: "#2a4860",
    accent: "#70a0b8",
    pattern: "stripe",
  }),
  F({
    id: "savelha",
    name: "Savelha",
    rarity: "common",
    minDepth: 8,
    maxDepth: 36,
    minWeight: 0.4,
    maxWeight: 2.0,
    value: 15,
    chance: 82,
    areas: ["open"],
    strength: 16,
    xp: 12,
    shape: "sardine",
    body: "#4a8898",
    belly: "#d8eef0",
    fin: "#e0a040",
    accent: "#88c0c8",
    pattern: "none",
  }),
  F({
    id: "pescada",
    name: "Pescada",
    rarity: "common",
    minDepth: 12,
    maxDepth: 50,
    minWeight: 0.7,
    maxWeight: 3.2,
    value: 18,
    chance: 78,
    areas: ["open", "deep"],
    strength: 18,
    xp: 14,
    shape: "tuna",
    body: "#c8c0a0",
    belly: "#f4f0dc",
    fin: "#908870",
    accent: "#e0d8b8",
    pattern: "scale",
  }),
  F({
    id: "voador",
    name: "Peixe-voador",
    rarity: "uncommon",
    minDepth: 0,
    maxDepth: 22,
    minWeight: 0.2,
    maxWeight: 0.9,
    value: 32,
    chance: 36,
    areas: ["open", "beach"],
    strength: 14,
    xp: 22,
    shape: "sardine",
    body: "#4aa0c8",
    belly: "#e0f4fa",
    fin: "#88d0e8",
    accent: "#206888",
    pattern: "none",
  }),
  F({
    id: "dourado",
    name: "Dourado",
    rarity: "uncommon",
    minDepth: 14,
    maxDepth: 55,
    minWeight: 1.5,
    maxWeight: 8.0,
    value: 48,
    chance: 28,
    areas: ["open"],
    strength: 32,
    xp: 30,
    shape: "marlin",
    body: "#e8c430",
    belly: "#f8e8a0",
    fin: "#2a8a6a",
    accent: "#40c090",
    pattern: "spot",
  }),
  F({
    id: "garoupa",
    name: "Garoupa",
    rarity: "uncommon",
    minDepth: 16,
    maxDepth: 60,
    minWeight: 1.8,
    maxWeight: 9.5,
    value: 52,
    chance: 26,
    areas: ["open", "reef"],
    strength: 34,
    xp: 32,
    shape: "round",
    body: "#c09058",
    belly: "#f0d8b0",
    fin: "#8a6038",
    accent: "#6a8a40",
    pattern: "spot",
  }),
  F({
    id: "atum-jovem",
    name: "Atum-jovem",
    rarity: "uncommon",
    minDepth: 20,
    maxDepth: 60,
    minWeight: 2.0,
    maxWeight: 10,
    value: 55,
    chance: 24,
    areas: ["open"],
    strength: 38,
    xp: 34,
    shape: "tuna",
    body: "#2a5a78",
    belly: "#c8dce8",
    fin: "#1a384c",
    accent: "#f0b040",
    pattern: "stripe",
  }),
  F({
    id: "lula",
    name: "Lula",
    rarity: "rare",
    minDepth: 16,
    maxDepth: 55,
    minWeight: 0.6,
    maxWeight: 4.0,
    value: 90,
    chance: 14,
    areas: ["open", "deep"],
    strength: 28,
    xp: 52,
    shape: "squid",
    body: "#d07090",
    belly: "#f0c0d0",
    fin: "#a04868",
    accent: "#f8e0e8",
    pattern: "none",
  }),
  F({
    id: "raia",
    name: "Raia",
    rarity: "rare",
    minDepth: 10,
    maxDepth: 48,
    minWeight: 2.0,
    maxWeight: 12,
    value: 110,
    chance: 12,
    areas: ["open", "reef"],
    strength: 30,
    xp: 58,
    shape: "ray",
    body: "#6a5a78",
    belly: "#d8d0e0",
    fin: "#4a3c58",
    accent: "#c0a0d0",
    pattern: "spot",
  }),
  F({
    id: "barracuda",
    name: "Barracuda",
    rarity: "rare",
    minDepth: 24,
    maxDepth: 60,
    minWeight: 2.5,
    maxWeight: 11,
    value: 130,
    chance: 11,
    areas: ["open", "reef"],
    strength: 44,
    xp: 64,
    shape: "swordfish",
    body: "#7aa0a8",
    belly: "#dce8ea",
    fin: "#4a6870",
    accent: "#c0d8dc",
    pattern: "stripe",
  }),
  F({
    id: "pargo",
    name: "Pargo",
    rarity: "epic",
    minDepth: 28,
    maxDepth: 60,
    minWeight: 2.0,
    maxWeight: 8.5,
    value: 260,
    chance: 4.5,
    areas: ["open", "reef"],
    strength: 40,
    xp: 130,
    shape: "round",
    body: "#d05050",
    belly: "#f0c0b8",
    fin: "#a03038",
    accent: "#f08078",
    pattern: "scale",
  }),
  F({
    id: "atum",
    name: "Atum",
    rarity: "epic",
    minDepth: 32,
    maxDepth: 70,
    minWeight: 8,
    maxWeight: 40,
    value: 340,
    chance: 3.6,
    areas: ["open", "deep"],
    strength: 58,
    xp: 160,
    shape: "tuna",
    body: "#1a4060",
    belly: "#b8d0e0",
    fin: "#0a2840",
    accent: "#e8a030",
    pattern: "stripe",
  }),
  F({
    id: "tubarao-lixa",
    name: "Tubarão-lixa",
    rarity: "legendary",
    minDepth: 40,
    maxDepth: 60,
    minWeight: 18,
    maxWeight: 70,
    value: 2200,
    chance: 0.65,
    areas: ["open"],
    strength: 72,
    xp: 480,
    shape: "shark",
    body: "#8a9aa8",
    belly: "#e0e8ee",
    fin: "#5a6a78",
    accent: "#c0c8d0",
    pattern: "none",
  }),

  F({
    id: "cirurgiao",
    name: "Peixe-cirurgião",
    rarity: "common",
    minDepth: 4,
    maxDepth: 40,
    minWeight: 0.2,
    maxWeight: 0.9,
    value: 18,
    chance: 80,
    areas: ["reef"],
    strength: 12,
    xp: 14,
    shape: "round",
    body: "#3a9ad0",
    belly: "#b8e0f4",
    fin: "#f0c430",
    accent: "#2080b0",
    pattern: "band",
  }),
  F({
    id: "donzela",
    name: "Donzela",
    rarity: "common",
    minDepth: 2,
    maxDepth: 30,
    minWeight: 0.08,
    maxWeight: 0.3,
    value: 16,
    chance: 78,
    areas: ["reef"],
    strength: 8,
    xp: 12,
    shape: "round",
    body: "#2a50c8",
    belly: "#c0d0f8",
    fin: "#1a38a0",
    accent: "#f0d040",
    pattern: "none",
  }),
  F({
    id: "papagaio",
    name: "Peixe-papagaio",
    rarity: "common",
    minDepth: 5,
    maxDepth: 45,
    minWeight: 0.5,
    maxWeight: 3.5,
    value: 22,
    chance: 70,
    areas: ["reef"],
    strength: 16,
    xp: 16,
    shape: "round",
    body: "#40c090",
    belly: "#c8f4e0",
    fin: "#e87090",
    accent: "#f0d060",
    pattern: "scale",
  }),
  F({
    id: "caranguejo",
    name: "Caranguejo",
    rarity: "common",
    minDepth: 0,
    maxDepth: 25,
    minWeight: 0.2,
    maxWeight: 1.4,
    value: 14,
    chance: 55,
    areas: ["reef", "beach"],
    strength: 10,
    xp: 11,
    shape: "crab",
    body: "#d05030",
    belly: "#f0b090",
    fin: "#a03018",
    accent: "#f0d0a0",
    pattern: "none",
  }),
  F({
    id: "anjo",
    name: "Peixe-anjo",
    rarity: "uncommon",
    minDepth: 6,
    maxDepth: 50,
    minWeight: 0.3,
    maxWeight: 1.6,
    value: 44,
    chance: 32,
    areas: ["reef"],
    strength: 14,
    xp: 26,
    shape: "round",
    body: "#f0c040",
    belly: "#fff0b8",
    fin: "#e070b0",
    accent: "#40a0e0",
    pattern: "band",
  }),
  F({
    id: "leao",
    name: "Peixe-leão",
    rarity: "uncommon",
    minDepth: 8,
    maxDepth: 55,
    minWeight: 0.3,
    maxWeight: 1.4,
    value: 58,
    chance: 24,
    areas: ["reef"],
    strength: 20,
    xp: 34,
    shape: "puffer",
    body: "#d8a040",
    belly: "#f8e0b0",
    fin: "#c04030",
    accent: "#f0d080",
    pattern: "stripe",
  }),
  F({
    id: "moreia",
    name: "Moreia",
    rarity: "uncommon",
    minDepth: 10,
    maxDepth: 70,
    minWeight: 1.5,
    maxWeight: 8.0,
    value: 64,
    chance: 22,
    areas: ["reef", "deep"],
    strength: 36,
    xp: 36,
    shape: "eel",
    body: "#4a6a58",
    belly: "#a8c4b0",
    fin: "#2a4438",
    accent: "#d0e070",
    pattern: "spot",
  }),
  F({
    id: "polvo",
    name: "Polvo",
    rarity: "rare",
    minDepth: 8,
    maxDepth: 60,
    minWeight: 1.2,
    maxWeight: 9.0,
    value: 140,
    chance: 12,
    areas: ["reef", "deep"],
    strength: 34,
    xp: 70,
    shape: "octopus",
    body: "#a04888",
    belly: "#e0a0c8",
    fin: "#782060",
    accent: "#f0c0e0",
    pattern: "spot",
  }),
  F({
    id: "mandarim",
    name: "Peixe-mandarim",
    rarity: "rare",
    minDepth: 4,
    maxDepth: 28,
    minWeight: 0.04,
    maxWeight: 0.12,
    value: 160,
    chance: 9,
    areas: ["reef"],
    strength: 8,
    xp: 78,
    shape: "round",
    body: "#2050c8",
    belly: "#40c0e0",
    fin: "#e07020",
    accent: "#f0d040",
    glow: "#60e0ff",
    pattern: "stripe",
  }),
  F({
    id: "napoleao",
    name: "Napoleão",
    rarity: "epic",
    minDepth: 20,
    maxDepth: 80,
    minWeight: 8,
    maxWeight: 45,
    value: 420,
    chance: 3.4,
    areas: ["reef"],
    strength: 62,
    xp: 180,
    shape: "round",
    body: "#e0a020",
    belly: "#f8e0a0",
    fin: "#c07018",
    accent: "#40b0a0",
    pattern: "scale",
  }),
  F({
    id: "tubarao-recife",
    name: "Tubarão-de-recife",
    rarity: "epic",
    minDepth: 18,
    maxDepth: 90,
    minWeight: 12,
    maxWeight: 55,
    value: 520,
    chance: 2.8,
    areas: ["reef"],
    strength: 68,
    xp: 200,
    shape: "shark",
    body: "#708898",
    belly: "#dce6ec",
    fin: "#4a6070",
    accent: "#a8c0cc",
    pattern: "none",
  }),
  F({
    id: "peixe-lua",
    name: "Peixe-lua",
    rarity: "legendary",
    minDepth: 40,
    maxDepth: 100,
    minWeight: 40,
    maxWeight: 220,
    value: 3200,
    chance: 0.55,
    areas: ["reef", "deep"],
    strength: 70,
    xp: 560,
    shape: "round",
    body: "#d0d8c8",
    belly: "#f4f8ee",
    fin: "#90a090",
    accent: "#b8c8b0",
    glow: "#e8f8c8",
    pattern: "none",
  }),

  F({
    id: "enguia",
    name: "Enguia",
    rarity: "common",
    minDepth: 30,
    maxDepth: 120,
    minWeight: 0.8,
    maxWeight: 4.5,
    value: 22,
    chance: 70,
    areas: ["deep"],
    strength: 22,
    xp: 16,
    shape: "eel",
    body: "#3a4a40",
    belly: "#8a9a88",
    fin: "#2a3830",
    accent: "#d0c060",
    pattern: "none",
  }),
  F({
    id: "congrio",
    name: "Congro",
    rarity: "common",
    minDepth: 40,
    maxDepth: 140,
    minWeight: 1.5,
    maxWeight: 8.0,
    value: 26,
    chance: 64,
    areas: ["deep"],
    strength: 28,
    xp: 18,
    shape: "eel",
    body: "#6a5040",
    belly: "#c0a890",
    fin: "#4a382c",
    accent: "#e0c8a0",
    pattern: "spot",
  }),
  F({
    id: "relogio",
    name: "Peixe-relógio",
    rarity: "uncommon",
    minDepth: 60,
    maxDepth: 160,
    minWeight: 0.4,
    maxWeight: 2.2,
    value: 70,
    chance: 28,
    areas: ["deep"],
    strength: 18,
    xp: 36,
    shape: "round",
    body: "#c8a048",
    belly: "#f0dc98",
    fin: "#8a6828",
    accent: "#e8c860",
    pattern: "band",
  }),
  F({
    id: "opah",
    name: "Opah",
    rarity: "uncommon",
    minDepth: 50,
    maxDepth: 150,
    minWeight: 8,
    maxWeight: 40,
    value: 90,
    chance: 20,
    areas: ["deep"],
    strength: 40,
    xp: 44,
    shape: "round",
    body: "#d04070",
    belly: "#f0b0c8",
    fin: "#e07040",
    accent: "#40c0d0",
    pattern: "spot",
  }),
  F({
    id: "espada",
    name: "Peixe-espada",
    rarity: "rare",
    minDepth: 70,
    maxDepth: 170,
    minWeight: 12,
    maxWeight: 55,
    value: 220,
    chance: 10,
    areas: ["deep"],
    strength: 64,
    xp: 90,
    shape: "swordfish",
    body: "#4a6a88",
    belly: "#c8d8e8",
    fin: "#2a4460",
    accent: "#90b0c8",
    pattern: "none",
  }),
  F({
    id: "marlin",
    name: "Marlin",
    rarity: "rare",
    minDepth: 55,
    maxDepth: 160,
    minWeight: 20,
    maxWeight: 90,
    value: 280,
    chance: 8,
    areas: ["deep", "open"],
    strength: 72,
    xp: 110,
    shape: "marlin",
    body: "#2a78c0",
    belly: "#c8e4f8",
    fin: "#1a4a88",
    accent: "#40a0e8",
    pattern: "stripe",
  }),
  F({
    id: "lula-grande",
    name: "Lula-grande",
    rarity: "rare",
    minDepth: 80,
    maxDepth: 180,
    minWeight: 6,
    maxWeight: 40,
    value: 240,
    chance: 9,
    areas: ["deep", "abyss"],
    strength: 50,
    xp: 96,
    shape: "squid",
    body: "#8850a0",
    belly: "#d0a8e0",
    fin: "#603078",
    accent: "#f0c8ff",
    pattern: "none",
  }),
  F({
    id: "atum-rabilho",
    name: "Atum-rabilho",
    rarity: "epic",
    minDepth: 60,
    maxDepth: 170,
    minWeight: 30,
    maxWeight: 140,
    value: 680,
    chance: 3.0,
    areas: ["deep"],
    strength: 80,
    xp: 220,
    shape: "tuna",
    body: "#163050",
    belly: "#a8c4d8",
    fin: "#0c1c30",
    accent: "#e89020",
    pattern: "stripe",
  }),
  F({
    id: "tubarao-azul",
    name: "Tubarão-azul",
    rarity: "epic",
    minDepth: 50,
    maxDepth: 160,
    minWeight: 25,
    maxWeight: 110,
    value: 740,
    chance: 2.6,
    areas: ["deep"],
    strength: 82,
    xp: 240,
    shape: "shark",
    body: "#2a6a9a",
    belly: "#d0e8f4",
    fin: "#1a4868",
    accent: "#68a8d0",
    pattern: "none",
  }),
  F({
    id: "tubarao-mako",
    name: "Tubarão-mako",
    rarity: "legendary",
    minDepth: 90,
    maxDepth: 180,
    minWeight: 40,
    maxWeight: 180,
    value: 4800,
    chance: 0.5,
    areas: ["deep"],
    strength: 92,
    xp: 700,
    shape: "shark",
    body: "#3a7088",
    belly: "#e0f0f4",
    fin: "#1a4458",
    accent: "#80c0d4",
    glow: "#80e0f0",
    pattern: "none",
  }),

  F({
    id: "lanterna",
    name: "Peixe-lanterna",
    rarity: "common",
    minDepth: 120,
    maxDepth: 260,
    minWeight: 0.05,
    maxWeight: 0.25,
    value: 36,
    chance: 80,
    areas: ["abyss"],
    strength: 10,
    xp: 22,
    shape: "sardine",
    body: "#1a3048",
    belly: "#3a6080",
    fin: "#0c1828",
    accent: "#c8f060",
    glow: "#d8ff70",
    pattern: "glow",
  }),
  F({
    id: "vibora",
    name: "Víbora-do-mar",
    rarity: "common",
    minDepth: 140,
    maxDepth: 280,
    minWeight: 0.3,
    maxWeight: 1.8,
    value: 40,
    chance: 62,
    areas: ["abyss"],
    strength: 24,
    xp: 24,
    shape: "eel",
    body: "#203040",
    belly: "#506070",
    fin: "#101820",
    accent: "#e07050",
    pattern: "none",
  }),
  F({
    id: "pelicano",
    name: "Peixe-pelicano",
    rarity: "uncommon",
    minDepth: 160,
    maxDepth: 290,
    minWeight: 0.4,
    maxWeight: 2.4,
    value: 95,
    chance: 26,
    areas: ["abyss"],
    strength: 22,
    xp: 48,
    shape: "angler",
    body: "#2a2438",
    belly: "#5a5070",
    fin: "#181422",
    accent: "#e8a060",
    pattern: "none",
  }),
  F({
    id: "quimera",
    name: "Quimera",
    rarity: "uncommon",
    minDepth: 130,
    maxDepth: 270,
    minWeight: 1.2,
    maxWeight: 6.0,
    value: 120,
    chance: 20,
    areas: ["abyss"],
    strength: 30,
    xp: 54,
    shape: "ray",
    body: "#3a4a68",
    belly: "#90a0c0",
    fin: "#243048",
    accent: "#c0d0f0",
    glow: "#a0c8ff",
    pattern: "glow",
  }),
  F({
    id: "diabo",
    name: "Peixe-diabo",
    rarity: "rare",
    minDepth: 180,
    maxDepth: 300,
    minWeight: 1.5,
    maxWeight: 9.0,
    value: 280,
    chance: 10,
    areas: ["abyss"],
    strength: 48,
    xp: 100,
    shape: "angler",
    body: "#1c1420",
    belly: "#4a3850",
    fin: "#100c14",
    accent: "#f0d060",
    glow: "#ffe080",
    pattern: "glow",
  }),
  F({
    id: "abissal",
    name: "Peixe-abissal",
    rarity: "rare",
    minDepth: 150,
    maxDepth: 290,
    minWeight: 0.8,
    maxWeight: 5.0,
    value: 260,
    chance: 11,
    areas: ["abyss"],
    strength: 40,
    xp: 96,
    shape: "sardine",
    body: "#142030",
    belly: "#3a5870",
    fin: "#0a141c",
    accent: "#40e0c8",
    glow: "#60ffe0",
    pattern: "glow",
  }),
  F({
    id: "vampiro",
    name: "Lula-vampiro",
    rarity: "epic",
    minDepth: 200,
    maxDepth: 300,
    minWeight: 4,
    maxWeight: 18,
    value: 820,
    chance: 2.8,
    areas: ["abyss"],
    strength: 58,
    xp: 240,
    shape: "squid",
    body: "#4a1028",
    belly: "#882040",
    fin: "#2a0814",
    accent: "#e04070",
    glow: "#ff6090",
    pattern: "glow",
  }),
  F({
    id: "duende",
    name: "Tubarão-duende",
    rarity: "epic",
    minDepth: 210,
    maxDepth: 300,
    minWeight: 30,
    maxWeight: 140,
    value: 960,
    chance: 2.2,
    areas: ["abyss", "trench"],
    strength: 78,
    xp: 280,
    shape: "shark",
    body: "#6a6070",
    belly: "#c8c0c8",
    fin: "#403848",
    accent: "#e8a0b0",
    pattern: "none",
  }),
  F({
    id: "celacanto",
    name: "Celacanto",
    rarity: "legendary",
    minDepth: 160,
    maxDepth: 280,
    minWeight: 20,
    maxWeight: 90,
    value: 6200,
    chance: 0.45,
    areas: ["abyss"],
    strength: 74,
    xp: 820,
    shape: "tuna",
    body: "#2a6a78",
    belly: "#a0d0d8",
    fin: "#1a4850",
    accent: "#70e0c0",
    glow: "#80f0d8",
    pattern: "scale",
  }),
  F({
    id: "dragao-mar",
    name: "Dragão-do-mar",
    rarity: "legendary",
    minDepth: 220,
    maxDepth: 300,
    minWeight: 8,
    maxWeight: 40,
    value: 7400,
    chance: 0.4,
    areas: ["abyss"],
    strength: 80,
    xp: 900,
    shape: "dragon",
    body: "#1a4038",
    belly: "#40a088",
    fin: "#0c2824",
    accent: "#80f0c0",
    glow: "#a0ffd8",
    pattern: "glow",
  }),

  F({
    id: "tripode",
    name: "Peixe-tripé",
    rarity: "common",
    minDepth: 280,
    maxDepth: 420,
    minWeight: 0.2,
    maxWeight: 1.2,
    value: 55,
    chance: 60,
    areas: ["trench"],
    strength: 14,
    xp: 28,
    shape: "sardine",
    body: "#243040",
    belly: "#586878",
    fin: "#141c28",
    accent: "#90b0c8",
    pattern: "none",
  }),
  F({
    id: "fantasma",
    name: "Peixe-fantasma",
    rarity: "uncommon",
    minDepth: 300,
    maxDepth: 460,
    minWeight: 0.4,
    maxWeight: 2.8,
    value: 160,
    chance: 24,
    areas: ["trench"],
    strength: 22,
    xp: 60,
    shape: "jellyfish",
    body: "#c8e8f8",
    belly: "#e8f8ff",
    fin: "#90c0d8",
    accent: "#60e0ff",
    glow: "#c0f4ff",
    pattern: "glow",
  }),
  F({
    id: "medusa",
    name: "Medusa-abissal",
    rarity: "rare",
    minDepth: 260,
    maxDepth: 440,
    minWeight: 1.0,
    maxWeight: 8.0,
    value: 360,
    chance: 10,
    areas: ["trench"],
    strength: 26,
    xp: 120,
    shape: "jellyfish",
    body: "#8860c8",
    belly: "#d0b0f8",
    fin: "#604098",
    accent: "#f0c0ff",
    glow: "#e0a0ff",
    pattern: "glow",
  }),
  F({
    id: "colossal",
    name: "Lula-colossal",
    rarity: "epic",
    minDepth: 320,
    maxDepth: 500,
    minWeight: 80,
    maxWeight: 400,
    value: 1400,
    chance: 2.0,
    areas: ["trench"],
    strength: 90,
    xp: 340,
    shape: "squid",
    body: "#4a2030",
    belly: "#8a4058",
    fin: "#2a1018",
    accent: "#e07090",
    glow: "#ff90b0",
    pattern: "none",
  }),
  F({
    id: "hidra",
    name: "Hidra-marinha",
    rarity: "epic",
    minDepth: 350,
    maxDepth: 500,
    minWeight: 40,
    maxWeight: 180,
    value: 1600,
    chance: 1.6,
    areas: ["trench"],
    strength: 88,
    xp: 360,
    shape: "octopus",
    body: "#205040",
    belly: "#50a080",
    fin: "#103028",
    accent: "#80f0c0",
    glow: "#60ffc8",
    pattern: "glow",
  }),
  F({
    id: "kraken-jovem",
    name: "Kraken-jovem",
    rarity: "legendary",
    minDepth: 380,
    maxDepth: 500,
    minWeight: 120,
    maxWeight: 500,
    value: 11000,
    chance: 0.35,
    areas: ["trench"],
    strength: 96,
    xp: 1100,
    shape: "octopus",
    body: "#301020",
    belly: "#702040",
    fin: "#180810",
    accent: "#e04070",
    glow: "#ff5080",
    pattern: "glow",
  }),
  F({
    id: "leviatan-menor",
    name: "Leviatã-menor",
    rarity: "legendary",
    minDepth: 400,
    maxDepth: 500,
    minWeight: 200,
    maxWeight: 800,
    value: 14000,
    chance: 0.28,
    areas: ["trench"],
    strength: 100,
    xp: 1300,
    shape: "leviathan",
    body: "#143050",
    belly: "#4080b0",
    fin: "#0c1c30",
    accent: "#70d0ff",
    glow: "#80e0ff",
    pattern: "glow",
  }),

  F({
    id: "espectro",
    name: "Espectro-azul",
    rarity: "uncommon",
    minDepth: 420,
    maxDepth: 620,
    minWeight: 0.6,
    maxWeight: 4.0,
    value: 280,
    chance: 28,
    areas: ["mystery"],
    strength: 28,
    xp: 80,
    shape: "sardine",
    body: "#2040a0",
    belly: "#80a0ff",
    fin: "#102070",
    accent: "#c0d0ff",
    glow: "#8090ff",
    pattern: "glow",
  }),
  F({
    id: "estelar",
    name: "Peixe-estelar",
    rarity: "rare",
    minDepth: 450,
    maxDepth: 680,
    minWeight: 1.5,
    maxWeight: 9.0,
    value: 640,
    chance: 10,
    areas: ["mystery"],
    strength: 36,
    xp: 160,
    shape: "round",
    body: "#101830",
    belly: "#304070",
    fin: "#080c1c",
    accent: "#f0e080",
    glow: "#ffe8a0",
    pattern: "spot",
  }),
  F({
    id: "voidfin",
    name: "Nadadeira-do-vazio",
    rarity: "rare",
    minDepth: 500,
    maxDepth: 720,
    minWeight: 3,
    maxWeight: 16,
    value: 780,
    chance: 8,
    areas: ["mystery"],
    strength: 48,
    xp: 180,
    shape: "eel",
    body: "#080818",
    belly: "#282848",
    fin: "#04040c",
    accent: "#c060ff",
    glow: "#d080ff",
    pattern: "glow",
  }),
  F({
    id: "auroralis",
    name: "Auroralis",
    rarity: "epic",
    minDepth: 480,
    maxDepth: 740,
    minWeight: 8,
    maxWeight: 40,
    value: 2200,
    chance: 2.2,
    areas: ["mystery"],
    strength: 60,
    xp: 400,
    shape: "marlin",
    body: "#104060",
    belly: "#40e0c8",
    fin: "#082838",
    accent: "#f0a0e0",
    glow: "#80ffe0",
    pattern: "glow",
  }),
  F({
    id: "guardiao",
    name: "Guardião",
    rarity: "epic",
    minDepth: 520,
    maxDepth: 760,
    minWeight: 50,
    maxWeight: 220,
    value: 2800,
    chance: 1.6,
    areas: ["mystery"],
    strength: 88,
    xp: 460,
    shape: "shark",
    body: "#202040",
    belly: "#6060a0",
    fin: "#101028",
    accent: "#f0d060",
    glow: "#ffe080",
    pattern: "glow",
  }),
  F({
    id: "wyrm",
    name: "Serpente Oceânica",
    rarity: "legendary",
    minDepth: 560,
    maxDepth: 780,
    minWeight: 180,
    maxWeight: 700,
    value: 18000,
    chance: 0.3,
    areas: ["mystery"],
    strength: 105,
    xp: 1500,
    shape: "dragon",
    body: "#183050",
    belly: "#40a0c8",
    fin: "#0c1828",
    accent: "#80ffe0",
    glow: "#a0fff0",
    pattern: "glow",
  }),
  F({
    id: "kraken",
    name: "Kraken",
    rarity: "legendary",
    minDepth: 600,
    maxDepth: 800,
    minWeight: 300,
    maxWeight: 1200,
    value: 24000,
    chance: 0.22,
    areas: ["mystery"],
    strength: 112,
    xp: 1800,
    shape: "octopus",
    body: "#200818",
    belly: "#601030",
    fin: "#10040c",
    accent: "#ff4068",
    glow: "#ff6080",
    pattern: "glow",
  }),
  F({
    id: "leviatan",
    name: "Leviatã",
    rarity: "mythic",
    minDepth: 640,
    maxDepth: 800,
    minWeight: 800,
    maxWeight: 2800,
    value: 52000,
    chance: 0.1,
    areas: ["mystery"],
    strength: 125,
    xp: 3200,
    shape: "leviathan",
    body: "#0c2038",
    belly: "#2080c0",
    fin: "#061020",
    accent: "#60e0ff",
    glow: "#80f0ff",
    pattern: "glow",
  }),
  F({
    id: "coronis",
    name: "Coronis",
    rarity: "mythic",
    minDepth: 700,
    maxDepth: 800,
    minWeight: 200,
    maxWeight: 900,
    value: 68000,
    chance: 0.07,
    areas: ["mystery"],
    strength: 120,
    xp: 3800,
    shape: "jellyfish",
    body: "#f8f0d0",
    belly: "#fff8e8",
    fin: "#e0c870",
    accent: "#f0a0c0",
    glow: "#fff4c0",
    pattern: "glow",
  }),
  F({
    id: "soberano",
    name: "Soberano do Abismo",
    rarity: "mythic",
    minDepth: 740,
    maxDepth: 800,
    minWeight: 1200,
    maxWeight: 4000,
    value: 90000,
    chance: 0.045,
    areas: ["mystery"],
    strength: 140,
    xp: 4800,
    shape: "whale",
    body: "#101018",
    belly: "#c0a050",
    fin: "#08080c",
    accent: "#ffe080",
    glow: "#ffe8a0",
    pattern: "glow",
  }),
];

export const FISH_BY_ID: Record<string, FishDef> = Object.fromEntries(
  FISH.map((f) => [f.id, f]),
);

export const MISSION_POOL: MissionDef[] = [
  { id: "c8", title: "Pesque 8 peixes", kind: "catch", target: 8, rewardMoney: 70, rewardXp: 40 },
  { id: "c15", title: "Pesque 15 peixes", kind: "catch", target: 15, rewardMoney: 150, rewardXp: 80 },
  { id: "c30", title: "Pesque 30 peixes", kind: "catch", target: 30, rewardMoney: 320, rewardXp: 150 },
  { id: "e400", title: "Ganhe $400", kind: "earn", target: 400, rewardMoney: 90, rewardXp: 50 },
  { id: "e2000", title: "Ganhe $2.000", kind: "earn", target: 2000, rewardMoney: 280, rewardXp: 110 },
  { id: "e8000", title: "Ganhe $8.000", kind: "earn", target: 8000, rewardMoney: 900, rewardXp: 220 },
  { id: "r2", title: "Capture 2 peixes raros", kind: "rare", target: 2, rewardMoney: 180, rewardXp: 90 },
  { id: "r5", title: "Capture 5 peixes raros", kind: "rare", target: 5, rewardMoney: 480, rewardXp: 180 },
  { id: "d30", title: "Alcance 30 metros", kind: "depth", target: 30, rewardMoney: 120, rewardXp: 60 },
  { id: "d80", title: "Alcance 80 metros", kind: "depth", target: 80, rewardMoney: 400, rewardXp: 140 },
  { id: "d200", title: "Alcance 200 metros", kind: "depth", target: 200, rewardMoney: 1400, rewardXp: 280 },
  { id: "s10", title: "Venda 10 peixes", kind: "sell", target: 10, rewardMoney: 80, rewardXp: 40 },
  { id: "s25", title: "Venda 25 peixes", kind: "sell", target: 25, rewardMoney: 220, rewardXp: 90 },
  { id: "p3", title: "Faça 3 fisgadas perfeitas", kind: "perfect", target: 3, rewardMoney: 160, rewardXp: 80 },
  { id: "p8", title: "Faça 8 fisgadas perfeitas", kind: "perfect", target: 8, rewardMoney: 420, rewardXp: 160 },
  {
    id: "shark",
    title: "Capture um tubarão",
    kind: "species",
    target: 1,
    speciesId: "tubarao",
    rewardMoney: 800,
    rewardXp: 220,
  },
];

export const ACHIEVEMENTS: AchievementDef[] = [
  { id: "first", title: "Primeira fisgada", blurb: "Capture seu primeiro peixe.", reward: 40 },
  { id: "c50", title: "Meio cento", blurb: "Capture 50 peixes.", reward: 200 },
  { id: "c200", title: "Maré cheia", blurb: "Capture 200 peixes.", reward: 800 },
  { id: "c1000", title: "Lenda do cais", blurb: "Capture 1.000 peixes.", reward: 4000 },
  { id: "rare1", title: "Algo brilhou", blurb: "Capture um peixe raro.", reward: 120 },
  { id: "epic1", title: "Épico", blurb: "Capture um peixe épico.", reward: 400 },
  { id: "leg1", title: "Lenda viva", blurb: "Capture um peixe lendário.", reward: 2000 },
  { id: "myth1", title: "Além do mapa", blurb: "Capture um peixe mítico.", reward: 12000 },
  { id: "d50", title: "Abaixo dos 50", blurb: "Pesque a 50 metros.", reward: 180 },
  { id: "d100", title: "Cem metros", blurb: "Pesque a 100 metros.", reward: 600 },
  { id: "d300", title: "Noite d'água", blurb: "Pesque a 300 metros.", reward: 2500 },
  { id: "col20", title: "Colecionador", blurb: "Descubra 20 espécies.", reward: 300 },
  { id: "col40", title: "Naturalista", blurb: "Descubra 40 espécies.", reward: 1200 },
  { id: "colall", title: "Enciclopédia", blurb: "Descubra todas as espécies.", reward: 25000 },
  { id: "m10k", title: "Bolso cheio", blurb: "Acumule $10.000 ganhos.", reward: 400 },
  { id: "m100k", title: "Armador", blurb: "Acumule $100.000 ganhos.", reward: 2500 },
  { id: "m1m", title: "Império", blurb: "Acumule $1.000.000 ganhos.", reward: 15000 },
  { id: "perf20", title: "Olho de lince", blurb: "20 fisgadas perfeitas.", reward: 500 },
  { id: "areas", title: "Sete mares", blurb: "Desbloqueie todas as áreas.", reward: 8000 },
  { id: "rods", title: "Arsenal", blurb: "Compre todas as varas.", reward: 10000 },
];

export const DAILY_REWARDS = [
  { money: 50, xp: 20 },
  { money: 120, xp: 40 },
  { money: 220, xp: 60 },
  { money: 400, xp: 90 },
  { money: 650, xp: 120 },
  { money: 1000, xp: 160 },
  { money: 2200, xp: 280 },
];

export const DEPTH_ZONES = [
  { from: 0, to: 10, name: "Água rasa" },
  { from: 10, to: 30, name: "Zona costeira" },
  { from: 30, to: 60, name: "Mar profundo" },
  { from: 60, to: 100, name: "Abismo" },
  { from: 100, to: 200, name: "Grande Abismo" },
  { from: 200, to: 9999, name: "Zona misteriosa" },
];

export function zoneName(depth: number): string {
  for (const z of DEPTH_ZONES) {
    if (depth >= z.from && depth < z.to) return z.name;
  }
  return DEPTH_ZONES[DEPTH_ZONES.length - 1]!.name;
}

export function rodById(id: string): RodDef {
  return RODS.find((r) => r.id === id) ?? RODS[0]!;
}
export function hookById(id: string): HookDef {
  return HOOKS.find((h) => h.id === id) ?? HOOKS[0]!;
}
export function lineById(id: string): LineDef {
  return LINES.find((l) => l.id === id) ?? LINES[0]!;
}
export function bagById(id: string): BagDef {
  return BAGS.find((b) => b.id === id) ?? BAGS[0]!;
}
export function areaById(id: string): AreaDef {
  return AREAS.find((a) => a.id === id) ?? AREAS[0]!;
}
export function fishById(id: string): FishDef | undefined {
  return FISH_BY_ID[id];
}

export function maxReach(rodId: string, lineId: string): number {
  return rodById(rodId).depth + lineById(lineId).depthBonus;
}

export function bagCap(bagId: string): number {
  return bagById(bagId).capacity;
}

export function rarityRank(r: Rarity): number {
  return RARITY_ORDER.indexOf(r);
}
